const ShortUniqueId = require("short-unique-id");
const Short = require("../models/shortModel");
const { Op } = require("sequelize");

const uid = new ShortUniqueId({ length: 5 });

const PORT = process.env.PORT;

/**
 * @swagger
 * components:
 *      schemas:
 *          Short:
 *              type: object
 *              required:
 *                  - name
 *                  - originalURL
 *                  - userId
 *              properties:
 *                  id:
 *                     type: integer
 *                     description: Auto-generated by the db
 *                  name:
 *                      type: string
 *                      description: The name of the short URL
 *                  originalURL:
 *                      type: string
 *                      description: The original link to be shortened
 *                  description:
 *                      type: string
 *                      description: This describes the original link.
 *                  clickedTimes:
 *                      type: integer
 *                      description: Calculates the total time the shortened link was clicked
 *                  shortened:
 *                      type: string
 *                      description: The new generated link
 *                  userId:
 *                      type: integer
 *                      description: The user that generated the link
 *          
 *   
 *          newShort: 
 *              type: object
 *              properties:
 *                  name:
 *                      type: string
 *                      description: The name of the short URL
 *                  originalURL:
 *                      type: string
 *                      description: The original link to be shortened
 *                  description:
 *                      type: string
 *                      description: This describes the original link.
 *   
 *          updateShort: 
 *              type: object
 *              properties:
 *                  name:
 *                      type: string
 *                      description: The name of the short URL
 *                  originalURL:
 *                      type: string
 *                      description: The original link to be shortened
 *                  description:
 *                      type: string
 *                      description: This describes the original link               
 */


/**
 * @swagger
 * tags:
 *   name: Shorts
 *   description: The short URL managing API
 */

/**
 * @swagger
 * /api/v1/short/search:
 *   get:
 *     summary: Search for a short URL by name
 *     description: Search for a short URL by name
 *     tags: [Shorts]
 *     parameters:
 *       - in: query
 *         name: name
 *         schema:
 *           type: string
 *         description: The name of the short URL to search for
 *     responses:
 *       '200':
 *         description: Successful operation
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 data:
 *                   type: object
 *                   description: The response object of the name searched
 *                 count:
 *                   type: integer
 *                   description: The count of the short URLs found
 *       '400':
 *         description: Invalid input
 *       '404':
 *         description: Short URLs not found
 *       '500':
 *         description: Internal server error
 */
const searchByName = async (req, res) => {
  try {
    const { name } = req.query;
    const user = req.user.id;
    if (!name) {
      return res
        .status(400)
        .json({ error: "Input the name of the short URL you want to search" });
    }
    const result = await Short.findAll({
      where: {
        name: {
          [Op.like]: `%${name}%`,
        },
        userId: user,
      },
    });
    const count = await Short.count({
      where: {
        name: {
          [Op.like]: `%${name}%`,
        },
        userId: user,
      },
    });
    if (!result || result.length === 0) {
      return res
        .status(404)
        .json({ error: "No short URLs were found with the specified name" });
    }
    return res.status(200).json({ data: { result }, count: { count } });
  } catch (error) {
    console.error("Error fetching short URLs:", error);
    return res.status(500).json({ error: "Failed to fetch short URLs" });
  }
};

/**
 * @swagger
 * /api/v1/short:
 *   get:
 *     summary: Get all short URLs
 *     description: Get all short URLs created by the user
 *     tags: [Shorts]
 *     responses:
 *       '200':
 *         description: Successful operation
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 shorts:
 *                   type: array
 *                   items:
 *                     $ref: '#/components/schemas/Short'
 *       '404':
 *         description: No short URLs found
 *       '500':
 *         description: Internal server error
 */
const allUserCreatedShort = async (req, res) => {
  try {
    const user = req.user.id;
    const shorts = await Short.findAll({ where: { userId: user } });
    if (!shorts) {
      return res
        .status(404)
        .json({ error: "You haven't created any short URLs" });
    }
    return res.status(200).json({ shorts });
  } catch (error) {
    console.error("Error fetching user's created short URLs:", error);
    return res
      .status(500)
      .json({ error: "Failed to fetch user's created short URLs" });
  }
};

/**
 * @swagger
 * /api/v1/short:
 *   post:
 *     summary: Create a short URL
 *     description: Create a new short URL
 *     tags: [Shorts]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *              $ref: "#/components/schemas/newShort"
 *     responses:
 *       '201':
 *         description: Short URL created successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Short'
 *       '400':
 *         description: Bad request
 *       '500':
 *         description: Internal server error
 */
const createShort = async (req, res) => {
  try {
    const { originalURL, name, description } = req.body;
    if (!(originalURL && name)) {
      return res
        .status(400)
        .json({ error: "The web address and name are required field" });
    }
    if (!isValidUrl(originalURL)) {
      return res.status(400).json({
        error: "Invalid URL format, please enter a valid website address",
      });
    }
    let genShort = `${req.protocol}://${req.hostname}:${PORT}/${uid.rnd()}`;
    const findShort = await Short.findOne({ where: { shortened: genShort } });
    if (findShort) {
      genShort = `${req.protocol}://${req.hostname}:${PORT}/${uid.rnd()}`;
    }
    const newShort = await Short.create({
      userId: req.user.id,
      originalURL: originalURL,
      name: name,
      description: description,
      shortened: genShort,
    });
    return res.status(201).json({ data: { newShort } });
  } catch (error) {
    console.log(error);
    if (error.name === "SequelizeForeignKeyConstraintError") {
      return res.status(400).json({
        error:
          "Invalid user ID provided. Check if you're logged out and log in again",
      });
    } else if (error.name === "SequelizeUniqueConstraintError") {
      return res.status(400).json({ error: "Short URL already exists" });
    } else if (error.name === "SequelizeValidationError") {
      return res
        .status(400)
        .json({ error: "Validation error: " + error.message });
    } else {
      return res.status(500).json({ error: "An unknown error has occurred" });
    }
  }
};

/**
 * @swagger
 * /api/v1/short/{id}:
 *   get:
 *     summary: Get a short URL by ID
 *     description: Get a short URL by its ID
 *     tags: [Shorts]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: ID of the short URL to get
 *     responses:
 *       '200':
 *         description: Successful operation
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Short'
 *       '404':
 *         description: Short URL not found
 *       '500':
 *         description: Internal server error
 */
const getShort = async (req, res) => {
  try {
    const userId = req.user.id;
    const shortId = req.params.id;
    const short = await Short.findOne({
      where: { userId: userId, id: shortId },
    });
    if (!short) {
      return res.status(404).json({ error: "The short URL not found" });
    }
    return res.status(200).json({ short });
  } catch (error) {
    console.error("Error fetching short URL:", error);
    return res.status(500).json({ error: "Failed to fetch short URL" });
  }
};

/**
 * @swagger
 * /api/v1/short/{id}:
 *   patch:
 *     summary: Update a short URL by ID
 *     description: Update a short URL by its ID
 *     tags: [Shorts]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: ID of the short URL to update
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/updateShort'
 *     responses:
 *       '200':
 *         description: Short URL updated successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Short'
 *       '400':
 *         description: Bad request
 *       '404':
 *         description: Short URL not found
 *       '500':
 *         description: Internal server error
 */
const updateShort = async (req, res) => {
  try {
    const userId = req.user.id;
    const shortId = req.params.id;
    const { name, originalURL, description } = req.body;
    const short = await Short.findOne({
      where: { userId: userId, id: shortId },
    });
    if (!short) {
      return res.status(404).json({ error: "The short URL doesn't exist" });
    }
    // const updateDetails = {
    //     name: name || short.name,
    //     description: description || short.description
    // }
    // const  updatedShort = await Short.update(updateDetails, { where: { id: shortId }, returning: true });
    short.name = name || short.name;
    short.description = description || short.description;
    short.originalURL = originalURL || short.originalURL;
    await short.save();

    return res
      .status(200)
      .json({ message: "Short URL updated successfully", short });
  } catch (error) {
    console.error("Error updating short URL:", error);
    return res.status(500).json({ error: "Failed to update short URL" });
  }
};

/**
 * @swagger
 * /api/v1/short/{id}:
 *   delete:
 *     summary: Delete a short URL by ID
 *     description: Delete a short URL by its ID
 *     tags: [Shorts]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: ID of the short URL to delete
 *     responses:
 *       '200':
 *         description: Short URL deleted successfully
 *       '404':
 *         description: Short URL not found
 *       '500':
 *         description: Internal server error
 */

const deleteShort = async (req, res) => {
  try {
    const userId = req.user.id;
    const shortId = req.params.id;
    const short = await Short.findOne({
      where: { userId: userId, id: shortId },
    });
    if (!short) {
      return res.status(404).json({ error: "The short URL doesn't exist" });
    }
    await short.destroy();
    return res.status(200).json({ message: "Short URL deleted successfully" });
  } catch (error) {
    console.error("Error deleting short URL:", error);
    return res.status(500).json({ error: "Failed to delete short URL" });
  }
};

/**
 * @swagger
 * /api/{short}:
 *   get:
 *     summary: Redirect to original URL from short URL
 *     description: Redirect to the original URL from the short URL
 *     tags: [Shorts]
 *     parameters:
 *       - in: path
 *         name: short
 *         required: true
 *         schema:
 *           type: string
 *         description: Short code of the URL to redirect to
 *     responses:
 *       '302':
 *         description: Redirect to the original URL
 *       '404':
 *         description: Short URL not found
 *       '500':
 *         description: Internal server error
 */
const redirectShort = async (req, res) => {
  try {
    const short = req.params.short;
    const _ = `${req.protocol}://${req.hostname}:${PORT}/${short}`;
    const findShort = await Short.findOne({ where: { shortened: _ } });
    if (!findShort) {
      return res.status(404).json({ error: "The link doesn't exist" });
    }

    findShort.increment("clickedTimes");
    return res.redirect(findShort.originalURL);
  } catch (error) {
    console.log(error);
    return res.status(500).json("An unknown error has occurred", error);
  }
};

const isValidUrl = (url) => {
  const urlRegex = /^(http|https):\/\/[^\s]+/;
  return urlRegex.test(url);
};

module.exports = {
  allUserCreatedShort,
  createShort,
  getShort,
  updateShort,
  deleteShort,
  redirectShort,
  searchByName,
};
